version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPO_URL

  build:
    commands:
      - echo "Building Docker image..."
      - cd analytics && docker build -t phucnh6-cd12355 .
      - docker tag phucnh6-cd12355:latest $ECR_REPO_URL:latest

  post_build:
    commands:
      - echo "Pushing Docker image to Amazon ECR..."
      - docker push $ECR_REPO_URL:latest

artifacts:
  files:
    - '**/*'
